server:
  port: 8082
spring:
  profiles:
    active: qa
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
springjpa:
  show-sql: true
welcome:
  message: Welcome to Spring Boot Tutorial


---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
springjpa:
  show-sql: true
welcome:
  message: Welcome to Spring Boot Tutorial
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans,features"

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
springjpa:
  show-sql: true
welcome:
  message: Welcome to Spring Boot Tutorial